// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ULUstateSample_cpp
Rcpp::List ULUstateSample_cpp(int m, const arma::ivec& s, const Rcpp::List& ZMUt, const arma::vec& s2, const arma::mat& P, bool SOS_random);
RcppExport SEXP _NetworkChange_ULUstateSample_cpp(SEXP mSEXP, SEXP sSEXP, SEXP ZMUtSEXP, SEXP s2SEXP, SEXP PSEXP, SEXP SOS_randomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ZMUt(ZMUtSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< bool >::type SOS_random(SOS_randomSEXP);
    rcpp_result_gen = Rcpp::wrap(ULUstateSample_cpp(m, s, ZMUt, s2, P, SOS_random));
    return rcpp_result_gen;
END_RCPP
}
// M_U_cpp
arma::cube M_U_cpp(const arma::mat& U1, const arma::mat& U2, const arma::mat& V);
RcppExport SEXP _NetworkChange_M_U_cpp(SEXP U1SEXP, SEXP U2SEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U1(U1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U2(U2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(M_U_cpp(U1, U2, V));
    return rcpp_result_gen;
END_RCPP
}
// M_U_list_cpp
arma::cube M_U_list_cpp(const Rcpp::List& U_list);
RcppExport SEXP _NetworkChange_M_U_list_cpp(SEXP U_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type U_list(U_listSEXP);
    rcpp_result_gen = Rcpp::wrap(M_U_list_cpp(U_list));
    return rcpp_result_gen;
END_RCPP
}
// compute_diag_correction_cpp
arma::mat compute_diag_correction_cpp(const arma::mat& U);
RcppExport SEXP _NetworkChange_compute_diag_correction_cpp(SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    rcpp_result_gen = Rcpp::wrap(compute_diag_correction_cpp(U));
    return rcpp_result_gen;
END_RCPP
}
// compute_L_matrix_cpp
arma::mat compute_L_matrix_cpp(const arma::cube& Z, const arma::mat& U, int T_dim, int R);
RcppExport SEXP _NetworkChange_compute_L_matrix_cpp(SEXP ZSEXP, SEXP USEXP, SEXP T_dimSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type T_dim(T_dimSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_L_matrix_cpp(Z, U, T_dim, R));
    return rcpp_result_gen;
END_RCPP
}
// updateU_cpp
arma::mat updateU_cpp(const Rcpp::IntegerVector& K, arma::mat U, const arma::mat& V, int R, const arma::cube& Zb, double s2, const arma::vec& eU, const arma::mat& iVU);
RcppExport SEXP _NetworkChange_updateU_cpp(SEXP KSEXP, SEXP USEXP, SEXP VSEXP, SEXP RSEXP, SEXP ZbSEXP, SEXP s2SEXP, SEXP eUSEXP, SEXP iVUSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Zb(ZbSEXP);
    Rcpp::traits::input_parameter< double >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eU(eUSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type iVU(iVUSEXP);
    rcpp_result_gen = Rcpp::wrap(updateU_cpp(K, U, V, R, Zb, s2, eU, iVU));
    return rcpp_result_gen;
END_RCPP
}
// updateUm_cpp
Rcpp::List updateUm_cpp(int ns, Rcpp::List U, const arma::mat& V, int R, const Rcpp::List& Zm, const Rcpp::List& Km, const Rcpp::List& ej, const arma::vec& s2, const Rcpp::List& eU, const Rcpp::List& iVU, const std::string& UL_Normal);
RcppExport SEXP _NetworkChange_updateUm_cpp(SEXP nsSEXP, SEXP USEXP, SEXP VSEXP, SEXP RSEXP, SEXP ZmSEXP, SEXP KmSEXP, SEXP ejSEXP, SEXP s2SEXP, SEXP eUSEXP, SEXP iVUSEXP, SEXP UL_NormalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Zm(ZmSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Km(KmSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ej(ejSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type eU(eUSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type iVU(iVUSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type UL_Normal(UL_NormalSEXP);
    rcpp_result_gen = Rcpp::wrap(updateUm_cpp(ns, U, V, R, Zm, Km, ej, s2, eU, iVU, UL_Normal));
    return rcpp_result_gen;
END_RCPP
}
// updateV_cpp
arma::mat updateV_cpp(const arma::cube& Zb, const arma::mat& U, int R, const Rcpp::IntegerVector& K, double s2, const arma::vec& eV, const arma::mat& iVV);
RcppExport SEXP _NetworkChange_updateV_cpp(SEXP ZbSEXP, SEXP USEXP, SEXP RSEXP, SEXP KSEXP, SEXP s2SEXP, SEXP eVSEXP, SEXP iVVSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type Zb(ZbSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eV(eVSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type iVV(iVVSEXP);
    rcpp_result_gen = Rcpp::wrap(updateV_cpp(Zb, U, R, K, s2, eV, iVV));
    return rcpp_result_gen;
END_RCPP
}
// updateVm_cpp
Rcpp::List updateVm_cpp(int ns, const Rcpp::List& U, const arma::mat& V, const Rcpp::List& Zm, const Rcpp::List& Km, int R, const arma::vec& s2, const Rcpp::List& eV, const Rcpp::List& iVV);
RcppExport SEXP _NetworkChange_updateVm_cpp(SEXP nsSEXP, SEXP USEXP, SEXP VSEXP, SEXP ZmSEXP, SEXP KmSEXP, SEXP RSEXP, SEXP s2SEXP, SEXP eVSEXP, SEXP iVVSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Zm(ZmSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Km(KmSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type eV(eVSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type iVV(iVVSEXP);
    rcpp_result_gen = Rcpp::wrap(updateVm_cpp(ns, U, V, Zm, Km, R, s2, eV, iVV));
    return rcpp_result_gen;
END_RCPP
}
// rMVNorm_cpp
arma::mat rMVNorm_cpp(int n, const arma::vec& mu, const arma::mat& Sigma);
RcppExport SEXP _NetworkChange_rMVNorm_cpp(SEXP nSEXP, SEXP muSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rMVNorm_cpp(n, mu, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// rmn_cpp
arma::mat rmn_cpp(const arma::mat& M, const arma::mat& Srow, const arma::mat& Scol);
RcppExport SEXP _NetworkChange_rmn_cpp(SEXP MSEXP, SEXP SrowSEXP, SEXP ScolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Srow(SrowSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Scol(ScolSEXP);
    rcpp_result_gen = Rcpp::wrap(rmn_cpp(M, Srow, Scol));
    return rcpp_result_gen;
END_RCPP
}
// GramSchmidt_cpp
arma::mat GramSchmidt_cpp(const arma::mat& U);
RcppExport SEXP _NetworkChange_GramSchmidt_cpp(SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    rcpp_result_gen = Rcpp::wrap(GramSchmidt_cpp(U));
    return rcpp_result_gen;
END_RCPP
}
// Unormal_cpp
arma::mat Unormal_cpp(const arma::mat& U1);
RcppExport SEXP _NetworkChange_Unormal_cpp(SEXP U1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U1(U1SEXP);
    rcpp_result_gen = Rcpp::wrap(Unormal_cpp(U1));
    return rcpp_result_gen;
END_RCPP
}
// rsmn_cpp
arma::mat rsmn_cpp(int m, int n);
RcppExport SEXP _NetworkChange_rsmn_cpp(SEXP mSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rsmn_cpp(m, n));
    return rcpp_result_gen;
END_RCPP
}
// updates2m_cpp
arma::vec updates2m_cpp(int ns, const Rcpp::List& Zm, const Rcpp::List& MU, double c0, double d0, const Rcpp::List& Km);
RcppExport SEXP _NetworkChange_updates2m_cpp(SEXP nsSEXP, SEXP ZmSEXP, SEXP MUSEXP, SEXP c0SEXP, SEXP d0SEXP, SEXP KmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Zm(ZmSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Km(KmSEXP);
    rcpp_result_gen = Rcpp::wrap(updates2m_cpp(ns, Zm, MU, c0, d0, Km));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NetworkChange_ULUstateSample_cpp", (DL_FUNC) &_NetworkChange_ULUstateSample_cpp, 6},
    {"_NetworkChange_M_U_cpp", (DL_FUNC) &_NetworkChange_M_U_cpp, 3},
    {"_NetworkChange_M_U_list_cpp", (DL_FUNC) &_NetworkChange_M_U_list_cpp, 1},
    {"_NetworkChange_compute_diag_correction_cpp", (DL_FUNC) &_NetworkChange_compute_diag_correction_cpp, 1},
    {"_NetworkChange_compute_L_matrix_cpp", (DL_FUNC) &_NetworkChange_compute_L_matrix_cpp, 4},
    {"_NetworkChange_updateU_cpp", (DL_FUNC) &_NetworkChange_updateU_cpp, 8},
    {"_NetworkChange_updateUm_cpp", (DL_FUNC) &_NetworkChange_updateUm_cpp, 11},
    {"_NetworkChange_updateV_cpp", (DL_FUNC) &_NetworkChange_updateV_cpp, 7},
    {"_NetworkChange_updateVm_cpp", (DL_FUNC) &_NetworkChange_updateVm_cpp, 9},
    {"_NetworkChange_rMVNorm_cpp", (DL_FUNC) &_NetworkChange_rMVNorm_cpp, 3},
    {"_NetworkChange_rmn_cpp", (DL_FUNC) &_NetworkChange_rmn_cpp, 3},
    {"_NetworkChange_GramSchmidt_cpp", (DL_FUNC) &_NetworkChange_GramSchmidt_cpp, 1},
    {"_NetworkChange_Unormal_cpp", (DL_FUNC) &_NetworkChange_Unormal_cpp, 1},
    {"_NetworkChange_rsmn_cpp", (DL_FUNC) &_NetworkChange_rsmn_cpp, 2},
    {"_NetworkChange_updates2m_cpp", (DL_FUNC) &_NetworkChange_updates2m_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_NetworkChange(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
